# Generated by Django 2.2.3 on 2019-10-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='citytranslation',
            name='source_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2, verbose_name='Source language'),
        ),
        migrations.AlterField(
            model_name='country',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='source_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2, verbose_name='Source language'),
        ),
        migrations.AlterField(
            model_name='region',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='regiontranslation',
            name='source_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2, verbose_name='Source language'),
        ),
    ]
